#!/bin/sh

# Conventional commit regex pattern e.g. matching 
# Merge <source branch> branch into <target branch>
# or
# <type><(optional scope)>: <description>
REGEX="^((Merge[\w -]+ branch into)|(Revert)|((build|chore|ci|docs|feat|fix|perf|ops|refactor|revert|style|test)(\(.*\))?!?:)) (.|\s|\r|\n)+"

FILE=`cat $1` # File containing the commit message

echo "Commit Message: ${FILE}"

if ! [[ $FILE =~ $REGEX ]]; then
	echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard.​"
	exit 1
else
	echo >&2 "Valid commit message."
fi
